version: "3"

services:
  web:
    build:
      context: .
      dockerfile: "./web/development.Dockerfile"
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/local/src
      - /usr/local/src/web/node_modules/